version: "3.5"
services:
  postgres:
    image: postgres:15
    container_name: mobdevbku_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
    volumes:
      - mobdevbku_appdb:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/mobdevbku/backend:0.1.0
    container_name: mobdevbku_backend
    environment:
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mobdevbku_db:5432/${POSTGRES_DB}?schema=public
    networks:
      - app_network
    ports:
      - 8080:8080
      
volumes:
  mobdevbku_appdb:

networks:
  app_network:
    driver: bridge