name: CI

on:
  pull_request:
    branches: ["master"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Image name MUST have a pattern like <org_name_lowercase>/<repo_name_lowercase>
  IMAGE_NAME: mobdevbku/backend
  IMAGE_TAG: 0.1.0
  # username login to ghcr MUST be organization's name in lower case
  ORG_USERNAME: mobdevbku

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest
      
      # TODO: ssh to a machine which is chosen to be host server and pull image from cloud to deploy
